# Generated by Django 5.1 on 2024-09-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birth_date_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitter',
            name='price',
        ),
    ]
