# Generated by Django 5.1 on 2024-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_petsitter_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='experience',
            field=models.CharField(choices=[('Меньше 1 года', 'Меньше 1 года'), ('От 1 до 3 лет', 'От 1 до 3 лет'), ('От 3 до 5 лет', 'От 3 до 5 лет'), ('Больше 5 лет', 'Больше 5 лет')], max_length=255),
        ),
    ]
