# Generated by Django 5.0.2 on 2024-11-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_city_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
