# Generated by Django 5.0.2 on 2024-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_petsitter_categories_petsitter_min_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
