# Generated by Django 5.1.4 on 2025-04-15 18:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_pet_owner'),
        ('users', '0013_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='categories',
            field=models.ManyToManyField(to='pet.category', verbose_name='Категории животных'),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='experience',
            field=models.CharField(choices=[('Меньше 1 года', 'Меньше 1 года'), ('От 1 до 3 лет', 'От 1 до 3 лет'), ('От 3 до 5 лет', 'От 3 до 5 лет'), ('Больше 5 лет', 'Больше 5 лет')], max_length=255, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_petsitter',
            field=models.BooleanField(default=False, verbose_name='Является петситтером'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.region', verbose_name='Регион'),
        ),
    ]
