# Generated by Django 5.0.2 on 2024-11-28 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='Пользователь не оставил комментарий к своей оценке', null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='review_photo', verbose_name='Фотография к отзыву')),
                ('video', models.FileField(blank=True, null=True, upload_to='review_video', verbose_name='Видео к отзыву')),
                ('published', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator_object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
