# Generated by Django 5.0.2 on 2024-12-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_review_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_review/', verbose_name='фотография к отзыву')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.review')),
            ],
        ),
    ]
