# Generated by Django 5.1.4 on 2024-12-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
