# Generated by Django 5.1 on 2024-09-05 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='pets/')),
                ('name', models.CharField(max_length=255)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.CharField(choices=[('<5', 'Легкий (до 5 кг)'), ('>5 & <15', 'Средний (до 15 кг)'), ('>20', 'Тяжелый (больше 15 кг)')], max_length=255)),
                ('certificate', models.BooleanField(default=False)),
                ('info', models.TextField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.breed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WeightChoices',
        ),
    ]
