# Generated by Django 5.1 on 2024-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_delete_weightchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='pets/default.jpg', upload_to='pets/'),
        ),
    ]
