# Generated by Django 5.0.2 on 2024-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
