# Generated by Django 5.1.4 on 2025-01-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
