# Generated by Django 5.1.4 on 2025-02-04 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pet_age_alter_pet_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.category', verbose_name='Категория животного'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название породы животного'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Возраст питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.breed', verbose_name='Порода питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.category', verbose_name='Категория питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='certificate',
            field=models.BooleanField(default=False, verbose_name='Сертификат с прививками'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='info',
            field=models.TextField(verbose_name='Дополнительная информация о питомце'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец Питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='pets/default.jpg', upload_to='pets/', verbose_name='Фотография питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес питомца'),
        ),
    ]
