# Generated by Django 5.1 on 2024-10-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dialogue_message_dialogue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dialogue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.dialogue'),
        ),
    ]
