# Generated by Django 5.1 on 2024-10-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_dialogue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dialogue_id',
            new_name='dialogue',
        ),
    ]
