# Generated by Django 5.0.2 on 2024-10-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsitterCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_frequency', models.IntegerField()),
                ('report_format_options', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Владелец', to=settings.AUTH_USER_MODEL)),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ситтер', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('Текст', 'Текст'), ('Фотография', 'Фотография'), ('Видео', 'Видео')], max_length=10)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='check_photo/', verbose_name='Фотография')),
                ('video', models.FileField(blank=True, null=True, upload_to='check_video/', verbose_name='Видео')),
                ('petsitter_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_system.petsittercheck')),
            ],
        ),
    ]
