# Generated by Django 5.0.2 on 2024-10-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0004_remove_petsittercheck_report_format_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
