# Generated by Django 5.0.2 on 2024-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0005_remove_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Текст', 'Текст'), ('Фотография', 'Фотография'), ('Видео', 'Видео')], default='Текст', max_length=10),
        ),
    ]
