# Generated by Django 5.0.2 on 2024-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0006_report_report_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsittercheck',
            old_name='report_frequency',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='petsittercheck',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='petsittercheck',
            name='report_format',
        ),
        migrations.RemoveField(
            model_name='petsittercheck',
            name='report_period',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='petsittercheck',
            name='interval',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='check_photo/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.FileField(upload_to='check_video/', verbose_name='Видео'),
        ),
    ]
