# Generated by Django 5.0.2 on 2024-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0007_rename_report_frequency_petsittercheck_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis',
            field=models.TextField(default='Почему-то нейросеть не смогла обработать изображение ситтера...', verbose_name='Анализ'),
        ),
    ]
