# Generated by Django 5.0.2 on 2024-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0009_petsittercheck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsittercheck',
            name='rest',
            field=models.IntegerField(default=-1),
        ),
    ]
