# Generated by Django 5.0.2 on 2024-12-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0010_petsittercheck_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='reject_video/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('В рассмотрении', 'В рассмотрении'), ('Отказано', 'Отказано'), ('Принято', 'Принято')], default='В рассмотрении', max_length=50)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_system.petsittercheck', verbose_name='Система проверки')),
            ],
        ),
        migrations.CreateModel(
            name='RejectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reject_image/')),
                ('reject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_system.reject')),
            ],
        ),
    ]
