# Generated by Django 5.1.4 on 2025-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0011_reject_rejectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsittercheck',
            name='status',
            field=models.CharField(choices=[('IN PROCESS', 'IN PROCESS'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='IN PROCESS', max_length=255),
        ),
    ]
