# Generated by Django 5.1.4 on 2025-04-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0012_alter_petsittercheck_status'),
        ('orders', '0017_alter_order_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsittercheck',
            name='end_date',
            field=models.DateField(verbose_name='Дата конца проверки'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='frequency',
            field=models.IntegerField(verbose_name='Частота отправки отчетов'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='interval',
            field=models.IntegerField(default=4, verbose_name='Интервал между отправкой отчетов'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Владелец', to=settings.AUTH_USER_MODEL, verbose_name='Владелец питомца'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='petsitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ситтер', to=settings.AUTH_USER_MODEL, verbose_name='Петситтер'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='rest',
            field=models.IntegerField(default=-1, verbose_name='Остаток количества отчетов'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала проверки'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='start_time',
            field=models.TimeField(default='12:00', verbose_name='Время начала отправки отчетов'),
        ),
        migrations.AlterField(
            model_name='petsittercheck',
            name='status',
            field=models.CharField(choices=[('IN PROCESS', 'IN PROCESS'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='IN PROCESS', max_length=255, verbose_name='Статус проверки'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='status',
            field=models.CharField(choices=[('В рассмотрении', 'В рассмотрении'), ('Отказано', 'Отказано'), ('Принято', 'Принято')], default='В рассмотрении', max_length=50, verbose_name='Статус отказа'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='text',
            field=models.TextField(verbose_name='Текст отказа'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отказа'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reject_video/', verbose_name='Видео отказа'),
        ),
        migrations.AlterField(
            model_name='rejectimage',
            name='image',
            field=models.ImageField(upload_to='reject_image/', verbose_name='Фото отказа'),
        ),
        migrations.AlterField(
            model_name='rejectimage',
            name='reject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_system.reject', verbose_name='Отказ от проверки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='analysis',
            field=models.TextField(default='Почему-то нейросеть не смогла обработать изображение ситтера...', verbose_name='Анализ видео отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='check_photo/', verbose_name='Фото отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='petsitter_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_system.petsittercheck', verbose_name='Система проверки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(verbose_name='Текст отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.FileField(upload_to='check_video/', verbose_name='Видео отчета'),
        ),
    ]
