# Generated by Django 5.1 on 2024-09-09 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0003_alter_pet_photo'),
        ('users', '0005_alter_user_birth_date_alter_user_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='pets/')),
                ('name', models.CharField(max_length=255)),
                ('need_walking', models.BooleanField(default=False)),
                ('need_sitting', models.BooleanField(default=True)),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.CharField(choices=[('<5', 'Легкий (до 5 кг)'), ('>5 & <15', 'Средний (до 15 кг)'), ('>20', 'Тяжелый (больше 15 кг)')], max_length=255)),
                ('certificate', models.BooleanField(default=False, verbose_name='Есть прививочный сертификат')),
                ('info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'В ождании'), ('accepted', 'Принято'), ('rejected', 'Отвергнуто')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.breed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.petsitter')),
            ],
        ),
    ]
