# Generated by Django 5.1 on 2024-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_updated_at_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ождании', 'В ождании'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=255),
        ),
    ]
