# Generated by Django 5.0.2 on 2024-12-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='need_sitting',
        ),
        migrations.RemoveField(
            model_name='order',
            name='need_walking',
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(choices=[('Передержка в доме у ситтера', 'Передержка в доме у ситтера'), ('Передержка у вас дома', 'Передержка у вас дома')], default='Передержка в доме у ситтера', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='walking',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
