# Generated by Django 5.1.4 on 2025-02-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_weight'),
        ('pet', '0007_alter_pet_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Возраст питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.breed', verbose_name='Категория питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.category', verbose_name='Возраст питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='certificate',
            field=models.BooleanField(default=False, verbose_name='Сертификат с прививками'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_day',
            field=models.DateField(verbose_name='Дата начала передержки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация о питомце'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_day',
            field=models.DateField(verbose_name='Дата конца передержки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='petsitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Петситтер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pets/', verbose_name='Фотография питомца'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(choices=[('Передержка в доме у ситтера', 'Передержка в доме у ситтера'), ('Передержка у вас дома', 'Передержка у вас дома')], default='Передержка в доме у ситтера', max_length=255, verbose_name='Место передержки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена передержки руб./день'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ождании'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=255, verbose_name='Статус объявления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='walking',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество необходимых выгулов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес питомца'),
        ),
    ]
