# Generated by Django 5.1.4 on 2025-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_age_alter_order_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, default='pets/default.jpg', upload_to='pets/', verbose_name='Фотография питомца'),
        ),
    ]
