# Generated by Django 5.1.4 on 2025-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(choices=[('Передержка в доме у ситтера', 'Petsitter Home'), ('Передержка у вас дома', 'Owner Home')], default='Передержка в доме у ситтера', max_length=255, verbose_name='Место передержки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'In Process'), ('Принято', 'Accepted'), ('Отклонено', 'Rejected')], default='В ожидании', max_length=255, verbose_name='Статус объявления'),
        ),
    ]
