# Generated by Django 5.1.4 on 2025-03-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_age_remove_order_breed_and_more'),
        ('pet', '0007_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='Питомец'),
        ),
    ]
