# Generated by Django 5.1.4 on 2025-03-11 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_pet'),
        ('pet', '0007_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(limit_choices_to={'owner': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец питомца')}, on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='Питомец'),
        ),
    ]
