# Generated by Django 5.1.4 on 2025-03-11 17:35

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_pet'),
        ('pet', '0007_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(limit_choices_to=django.db.models.expressions.OuterRef('user'), on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='Питомец'),
        ),
    ]
