# Generated by Django 5.1.4 on 2025-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(choices=[('Передержка в доме у ситтера', 'Передержка в доме у ситтера'), ('Передержка у вас дома', 'Передержка у вас дома')], default='Передержка в доме у ситтера', max_length=255, verbose_name='Место передержки'),
        ),
    ]
