# Generated by Django 5.0.2 on 2024-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'system'), ('order', 'order')], max_length=255),
        ),
    ]
