# Generated by Django 5.0.2 on 2024-11-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='system_id',
            new_name='object_id',
        ),
    ]
