# Generated by Django 5.0.2 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_object_id_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
