# Generated by Django 5.1.4 on 2024-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('report_load', 'report_load'), ('report_watch', 'report_watch'), ('order_created', 'order_created'), ('order_status', 'order_status'), ('review', 'review'), ('other', 'other')], max_length=255),
        ),
    ]
