# Generated by Django 5.1.4 on 2025-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
